language: python
python:
    - "3.5"

install:
    # Install requirements and this package
    - bash install.sh
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda activate ps2ff
script:
    - export PYTHONPATH="."
    - py.test --cov=.
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
